server:
  port: 8888  # Port de l'API Gateway

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # Gestion en minuscules automatique des noms de services

      routes:
        - id: enrollmentservice
          uri: lb://enrollmentservice
          predicates:
            - Path=/api/enrollments/**

        - id: studentservice
          uri: lb://studentservice
          predicates:
            - Path=/students/**

        - id: courseservice
          uri: lb://courseservice
          predicates:
            - Path=/courses/**

        - id: notificationservice
          uri: lb://notificationservice
          predicates:
            - Path=/api/notifications/**

        - id: paymentservice
          uri: lb://paymentservice
          predicates:
            - Path=/payments/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

# NotchPay API configuration
notchpay:
  public:
    key: pk_test.KjC8jAHnbEYAVO1G7W1ReA3cjQJNxFRiaJq1dSXT97NQ0srxwlh0qvDMK1nVaamcPUasOXqpn2PcQQbx0IjQDqB0auG7lw2JI5c0vMFG7pECoIZZkZ0RmsBxaP4b5
  secret:
    key: Bearer sk_test.1MH6J4mgrGPo6KMX7zRdAXq0FaGScwrPMyerv098lJexUAGPTxShqioFvnyUfLU8m0emXghluKHV1hRfEbmX9ujgqsquxIQWwGczHQOEtWHcMBewTiNn4eXQaxuiG
  api:
    url: https://api.notchpay.co
